"""From-scratch closed-form physics primitives — Project X Phase 13 cycle 4 (#00P13c4-02).

Substrate Tier 2 extension. Mirrors the cycle 2 + 3 maths substrate shape (`symbolic.py`):
each primitive returns a Lemma with intro prose (math-WHY) + derivation chain (WHAT) +
post-derivation invariant check (structural-insight criterion). Hand-rolled — uses only
Python stdlib `math` (√, π) — NO scipy.constants, NO pretrained-LLM-derived physics
engines, NO numerical-physics libraries.

Three primitives, ordered by ascending substrate complexity:
  - `free_fall_time(h, g)` — kinematic-identity closed form (1 sqrt; Newtonian mechanics)
  - `pendulum_period(L, g)` — small-angle SHM closed form (1 sqrt + π; Lagrangian linearization)
  - `relativistic_momentum(m, v, c)` — Lorentz-factor + p=γmv (2-step; special-relativistic dynamics)

Anti-cheat-aware design (cycle 4 #00P13c4-24 binding):
Each primitive computes from inputs at call-time — no hardcoded answer-lookups. The cycle 4
anti-cheat probes (in `tests/test_reasoning_physics.py`) verify `memorization_signal == 0.0`
across surrogate input families: free-fall from different heights/gravities (Earth, Moon,
Mars, Jupiter); pendulums of varying length; relativistic momentum across electron / proton
mass scales + velocities (0.1c → 0.99c). A substrate that hardcoded e.g. physics-001's
4.04s answer would fail the surrogate-pass-rate gate.

Identity discipline:
The agent (Project X Raphael) consumes these primitives at inference time to build
gradeable physics derivations. The builder (Claude Code Raphael) writes the substrate +
grades the output via the manual-grade harness, with M-PROJECTX-014 firewall (no
`self_score` on candidates) + cycle 4 anti-cheat probes (no canonical-answer overfit).
"""

from __future__ import annotations

import math

from project_x.reasoning.symbolic import Lemma


# Math-WHY prose constants — derivation of each formula from first principles.
# Per-primitive canned text (cycle 2 / cycle 3 pattern); NOT autogenerated.
# Renders before the derivation chain via Lemma.add_introduction.

INTRO_FREE_FALL = (
    "From rest under constant gravitational acceleration g, the kinematic identity is "
    "h = (1/2)·g·t² (integrating dv/dt = g twice with v(0) = 0 and x(0) = 0). Solving "
    "for t when the object has fallen height h gives t = √(2h/g). The form is independent "
    "of mass (Galileo's equivalence — all masses fall at the same rate in vacuum), and "
    "only valid in the no-air-resistance regime. The result scales like √h for fixed g "
    "and like 1/√g for fixed h."
)

INTRO_PENDULUM = (
    "A simple pendulum of length L under gravity g has Lagrangian "
    "L = (1/2)·m·L²·θ̇² - m·g·L·(1 - cos θ). Euler-Lagrange yields θ̈ + (g/L)·sin θ = 0. "
    "Small-angle linearization sin θ ≈ θ gives θ̈ + (g/L)·θ = 0 — simple harmonic motion "
    "with angular frequency ω = √(g/L). The period is T = 2π/ω = 2π·√(L/g). Mass drops "
    "out (equivalence principle); period depends only on L and g."
)

INTRO_RELATIVISTIC_MOMENTUM = (
    "Special relativity replaces Newton's p = m·v with p = γ·m·v, where the Lorentz factor "
    "γ = 1/√(1 - v²/c²). γ arises from the invariance of the spacetime interval ds² = "
    "c²·dτ² (proper time τ vs coordinate time t differ by γ = dt/dτ); the relativistic "
    "four-momentum's spatial components reduce to γmv in 3-vector form. In the v << c "
    "limit, γ → 1 and p → mv — Newtonian momentum is the slow-velocity limit, not a "
    "different law. Diverges as v → c (massive particle can never reach light speed)."
)


def free_fall_time(h: float, g: float, lemma_id: str = "free_fall_time") -> Lemma:
    """Compute free-fall time from height h under gravity g.

    Returns a Lemma with the kinematic-identity derivation chain + post-derivation
    invariant check (final velocity v_f = g·t should equal √(2·g·h) by energy
    conservation in the no-air-resistance regime).

    Raises ValueError on non-positive h or g (regime check; cycle 4 minimum-viable
    scope is the standard h>0, g>0 case).
    """
    if h <= 0 or g <= 0:
        raise ValueError(f"h and g must be positive (got h={h}, g={g})")

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute free-fall time from height {h} m under gravity {g} m/s².",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_FREE_FALL)

    inner = 2 * h / g
    lemma.add_step(
        operation="free_fall_inner",
        inputs={"h": h, "g": g},
        output=inner,
        justification=f"2h/g = 2·{h}/{g} = {inner}",
    )

    t = math.sqrt(inner)
    lemma.add_step(
        operation="sqrt",
        inputs={"inner": inner},
        output=t,
        justification=f"t = √(2h/g) = √{inner} = {t} s",
    )

    lemma.actual_value = t

    # Energy-conservation invariant: v_f = g·t at impact should equal √(2·g·h)
    # (from (1/2)·m·v_f² = m·g·h cancelling mass). Independent identity — doesn't
    # use the t we just computed except to recompute v_f.
    v_final_via_t = g * t
    v_final_via_energy = math.sqrt(2 * g * h)
    lemma.add_invariant_check(
        predicate="v_f = g·t = √(2·g·h) (energy conservation)",
        expected_value=v_final_via_energy,
        actual_value=v_final_via_t,
        justification=(
            "Energy conservation: (1/2)·m·v_f² = m·g·h; cancels mass; v_f = √(2gh). "
            "Independently computable from t via v_f = g·t. Both expressions must agree."
        ),
    )

    return lemma


def pendulum_period(L: float, g: float, lemma_id: str = "pendulum_period") -> Lemma:
    """Compute small-angle pendulum period T = 2π·√(L/g).

    Returns a Lemma with the Lagrangian-linearization derivation chain + invariant
    check (dimensionless quantity T²·g/L should equal 4π² — universal across all
    pendulum-and-gravity configurations).

    Raises ValueError on non-positive L or g.
    """
    if L <= 0 or g <= 0:
        raise ValueError(f"L and g must be positive (got L={L}, g={g})")

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute small-angle pendulum period for L = {L} m, g = {g} m/s².",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_PENDULUM)

    inner = L / g
    lemma.add_step(
        operation="period_inner",
        inputs={"L": L, "g": g},
        output=inner,
        justification=f"L/g = {L}/{g} = {inner}",
    )

    period = 2 * math.pi * math.sqrt(inner)
    lemma.add_step(
        operation="period_formula",
        inputs={"inner": inner},
        output=period,
        justification=f"T = 2π·√(L/g) = 2π·√{inner} = {period} s",
    )

    lemma.actual_value = period

    # Dimensionless invariant: T²·g/L = 4π² (universal — independent of L and g).
    # Provides the "Edge cases addressed" structural-insight surface: derivation
    # produces a quantity that, when scaled by the physical parameters, yields a
    # universal constant. Any drift from 4π² ≈ 39.478 signals a math bug.
    dimensionless = (period * period * g) / L
    lemma.add_invariant_check(
        predicate="T²·g/L = 4π² (dimensionless universal)",
        expected_value=4 * math.pi * math.pi,
        actual_value=dimensionless,
        justification=(
            "From T = 2π·√(L/g): T² = 4π²·L/g, so T²·g/L = 4π². Universal across "
            "all pendulum configurations — independent of L and g separately."
        ),
    )

    return lemma


def relativistic_momentum(
    m: float, v: float, c: float, lemma_id: str = "relativistic_momentum",
) -> Lemma:
    """Compute relativistic momentum p = γ·m·v with γ = 1/√(1 - v²/c²).

    Two-step derivation chain: Lorentz factor γ → momentum γmv. Invariant check:
    Newtonian limit (γ approaches 1 as v << c, giving p → m·v) — verifies the
    relativistic formula reduces to the classical formula in the slow-velocity
    limit (correspondence principle).

    Raises ValueError on non-positive m or c, or on |v| >= c (causal-structure
    violation; cycle 4 scope is subluminal v only).
    """
    if m <= 0 or c <= 0:
        raise ValueError(f"m and c must be positive (got m={m}, c={c})")
    if abs(v) >= c:
        raise ValueError(
            f"|v| must be < c for subluminal regime (got v={v}, c={c}); "
            f"superluminal not in cycle 4 scope",
        )

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute relativistic momentum for m = {m} kg at v = {v} m/s (c = {c} m/s).",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_RELATIVISTIC_MOMENTUM)

    beta_sq = (v * v) / (c * c)
    gamma = 1.0 / math.sqrt(1 - beta_sq)
    lemma.add_step(
        operation="lorentz_factor",
        inputs={"v": v, "c": c},
        output=gamma,
        justification=(
            f"β² = (v/c)² = ({v}/{c})² = {beta_sq}; γ = 1/√(1 - β²) = 1/√{1 - beta_sq} "
            f"= {gamma}"
        ),
    )

    p = gamma * m * v
    lemma.add_step(
        operation="momentum",
        inputs={"gamma": gamma, "m": m, "v": v},
        output=p,
        justification=f"p = γ·m·v = {gamma}·{m}·{v} = {p} kg·m/s",
    )

    lemma.actual_value = p

    # Newtonian-limit invariant: relativistic p / (m·v) = γ; γ → 1 as v << c.
    # We compute the relative correction (γ - 1) and verify it matches the
    # leading-order Taylor expansion β²/2 = (v/c)²/2 to within tolerance scaling
    # with β² (higher-order terms drift the comparison at relativistic speeds, so
    # the check is meaningful only at low v; in the relativistic regime, the
    # correspondence-principle test isn't a strict equality but a regime check).
    relative_correction = gamma - 1.0
    leading_order_approx = beta_sq / 2.0
    lemma.add_invariant_check(
        predicate="γ - 1 ≈ β²/2 in slow-velocity limit (Newtonian limit / correspondence)",
        expected_value=leading_order_approx,
        actual_value=relative_correction,
        justification=(
            "Taylor expansion: γ = 1 + β²/2 + 3β⁴/8 + ... → γ - 1 ≈ β²/2 in v << c. "
            "Holds exactly in the limit; check confirms substrate produced relativistic "
            "γ, not Newtonian γ=1. At relativistic v (e.g. 0.9c), higher-order terms "
            "dominate — invariant_check tolerance must be set per-call accordingly."
        ),
    )

    return lemma
