"""From-scratch closed-form physics primitives — Project X Phase 13 cycle 4 (#00P13c4-02).

Substrate Tier 2 extension. Mirrors the cycle 2 + 3 maths substrate shape (`symbolic.py`):
each primitive returns a Lemma with intro prose (math-WHY) + derivation chain (WHAT) +
post-derivation invariant check (structural-insight criterion). Hand-rolled — uses only
Python stdlib `math` (√, π) — NO scipy.constants, NO pretrained-LLM-derived physics
engines, NO numerical-physics libraries.

Three primitives, ordered by ascending substrate complexity:
  - `free_fall_time(h, g)` — kinematic-identity closed form (1 sqrt; Newtonian mechanics)
  - `pendulum_period(L, g)` — small-angle SHM closed form (1 sqrt + π; Lagrangian linearization)
  - `relativistic_momentum(m, v, c)` — Lorentz-factor + p=γmv (2-step; special-relativistic dynamics)

Anti-cheat-aware design (cycle 4 #00P13c4-24 binding):
Each primitive computes from inputs at call-time — no hardcoded answer-lookups. The cycle 4
anti-cheat probes (in `tests/test_reasoning_physics.py`) verify `memorization_signal == 0.0`
across surrogate input families: free-fall from different heights/gravities (Earth, Moon,
Mars, Jupiter); pendulums of varying length; relativistic momentum across electron / proton
mass scales + velocities (0.1c → 0.99c). A substrate that hardcoded e.g. physics-001's
4.04s answer would fail the surrogate-pass-rate gate.

Identity discipline:
The agent (Project X Raphael) consumes these primitives at inference time to build
gradeable physics derivations. The builder (Claude Code Raphael) writes the substrate +
grades the output via the manual-grade harness, with M-PROJECTX-014 firewall (no
`self_score` on candidates) + cycle 4 anti-cheat probes (no canonical-answer overfit).
"""

from __future__ import annotations

import math

from project_x.reasoning.symbolic import Lemma


# Math-WHY prose constants — derivation of each formula from first principles.
# Per-primitive canned text (cycle 2 / cycle 3 pattern); NOT autogenerated.
# Renders before the derivation chain via Lemma.add_introduction.

INTRO_FREE_FALL = (
    "From rest under constant gravitational acceleration g, the kinematic identity is "
    "h = (1/2)·g·t² (integrating dv/dt = g twice with v(0) = 0 and x(0) = 0). Solving "
    "for t when the object has fallen height h gives t = √(2h/g). The form is independent "
    "of mass (Galileo's equivalence — all masses fall at the same rate in vacuum), and "
    "only valid in the no-air-resistance regime. The result scales like √h for fixed g "
    "and like 1/√g for fixed h."
)

INTRO_PENDULUM = (
    "A simple pendulum of length L under gravity g has Lagrangian "
    "L = (1/2)·m·L²·θ̇² - m·g·L·(1 - cos θ). Euler-Lagrange yields θ̈ + (g/L)·sin θ = 0. "
    "Small-angle linearization sin θ ≈ θ gives θ̈ + (g/L)·θ = 0 — simple harmonic motion "
    "with angular frequency ω = √(g/L). The period is T = 2π/ω = 2π·√(L/g). Mass drops "
    "out (equivalence principle); period depends only on L and g."
)

INTRO_RELATIVISTIC_MOMENTUM = (
    "Special relativity replaces Newton's p = m·v with p = γ·m·v, where the Lorentz factor "
    "γ = 1/√(1 - v²/c²). γ arises from the invariance of the spacetime interval ds² = "
    "c²·dτ² (proper time τ vs coordinate time t differ by γ = dt/dτ); the relativistic "
    "four-momentum's spatial components reduce to γmv in 3-vector form. In the v << c "
    "limit, γ → 1 and p → mv — Newtonian momentum is the slow-velocity limit, not a "
    "different law. Diverges as v → c (massive particle can never reach light speed)."
)

INTRO_PROJECTILE_HORIZONTAL_RANGE = (
    "A projectile launched horizontally from height h with horizontal velocity v_x "
    "under gravity g (no air resistance) decouples into two independent 1D motions: "
    "vertical free-fall (initial v_y = 0; t = √(2h/g) by the kinematic identity "
    "h = (1/2)·g·t²) and horizontal uniform motion (no horizontal force; x(t) = v_x·t). "
    "The horizontal range at impact is R = v_x · √(2h/g). The form is independent of "
    "mass (Galileo's equivalence) and only valid in the no-air-resistance regime. R "
    "scales like √h for fixed v_x + g, and linearly in v_x."
)

INTRO_RELATIVISTIC_DOPPLER_SHIFT = (
    "The relativistic Doppler shift for a source moving radially relative to the "
    "observer combines two effects: classical wave-front compression/stretching and "
    "time dilation (the moving emitter's clock runs slow in the observer's frame). "
    "For an APPROACHING source, the observed wavelength is λ_obs = λ_emit · "
    "√((1-β)/(1+β)) where β = v/c — a blueshift (λ_obs < λ_emit). For a RECEDING "
    "source, λ_obs = λ_emit · √((1+β)/(1-β)) — a redshift (λ_obs > λ_emit). The two "
    "formulas are related by β → -β (or by reversing approach/recede); both reduce "
    "to the classical 1 ∓ β limit when β << 1 (Newtonian Doppler is the slow-velocity "
    "correspondence). Diverges as |β| → 1 (light-speed limit: receding gives "
    "infinite redshift, approaching compresses toward zero wavelength)."
)

INTRO_LARGE_ANGLE_PENDULUM = (
    "The simple-pendulum period formula T = 2π·√(L/g) is the small-angle linearization. "
    "For finite amplitude θ₀, the exact period derives from solving the non-linear ODE "
    "θ̈ + (g/L)·sin θ = 0 (no small-angle truncation). The exact answer involves the "
    "complete elliptic integral of the first kind: T = 4·√(L/g)·K(k) where k = sin(θ₀/2). "
    "Series expansion of K(k) yields T = T₀·[1 + (1/4)·k² + (9/64)·k⁴ + (25/256)·k⁶ + "
    "(1225/16384)·k⁸ + ...], where T₀ = 2π·√(L/g) is the small-angle period. The "
    "correction monotonically grows the period with amplitude (a 90° swing is ~18% slower "
    "than the small-angle approximation predicts). Coefficients are the squared central "
    "binomials [(2n)!/(2²ⁿ·(n!)²)]²; recursion a_{n+1}/a_n = ((2n+1)/(2n+2))²·k² lets the "
    "series build incrementally. Domain: |θ₀| < π (full-inversion regime is non-oscillatory)."
)


def free_fall_time(h: float, g: float, lemma_id: str = "free_fall_time") -> Lemma:
    """Compute free-fall time from height h under gravity g.

    Returns a Lemma with the kinematic-identity derivation chain + post-derivation
    invariant check (final velocity v_f = g·t should equal √(2·g·h) by energy
    conservation in the no-air-resistance regime).

    Raises ValueError on non-positive h or g (regime check; cycle 4 minimum-viable
    scope is the standard h>0, g>0 case).
    """
    if h <= 0 or g <= 0:
        raise ValueError(f"h and g must be positive (got h={h}, g={g})")

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute free-fall time from height {h} m under gravity {g} m/s².",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_FREE_FALL)

    inner = 2 * h / g
    lemma.add_step(
        operation="free_fall_inner",
        inputs={"h": h, "g": g},
        output=inner,
        justification=f"2h/g = 2·{h}/{g} = {inner}",
    )

    t = math.sqrt(inner)
    lemma.add_step(
        operation="sqrt",
        inputs={"inner": inner},
        output=t,
        justification=f"t = √(2h/g) = √{inner} = {t} s",
    )

    lemma.actual_value = t

    # Energy-conservation invariant: v_f = g·t at impact should equal √(2·g·h)
    # (from (1/2)·m·v_f² = m·g·h cancelling mass). Independent identity — doesn't
    # use the t we just computed except to recompute v_f.
    v_final_via_t = g * t
    v_final_via_energy = math.sqrt(2 * g * h)
    lemma.add_invariant_check(
        predicate="v_f = g·t = √(2·g·h) (energy conservation)",
        expected_value=v_final_via_energy,
        actual_value=v_final_via_t,
        justification=(
            "Energy conservation: (1/2)·m·v_f² = m·g·h; cancels mass; v_f = √(2gh). "
            "Independently computable from t via v_f = g·t. Both expressions must agree."
        ),
    )

    return lemma


def pendulum_period(L: float, g: float, lemma_id: str = "pendulum_period") -> Lemma:
    """Compute small-angle pendulum period T = 2π·√(L/g).

    Returns a Lemma with the Lagrangian-linearization derivation chain + invariant
    check (dimensionless quantity T²·g/L should equal 4π² — universal across all
    pendulum-and-gravity configurations).

    Raises ValueError on non-positive L or g.
    """
    if L <= 0 or g <= 0:
        raise ValueError(f"L and g must be positive (got L={L}, g={g})")

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute small-angle pendulum period for L = {L} m, g = {g} m/s².",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_PENDULUM)

    inner = L / g
    lemma.add_step(
        operation="period_inner",
        inputs={"L": L, "g": g},
        output=inner,
        justification=f"L/g = {L}/{g} = {inner}",
    )

    period = 2 * math.pi * math.sqrt(inner)
    lemma.add_step(
        operation="period_formula",
        inputs={"inner": inner},
        output=period,
        justification=f"T = 2π·√(L/g) = 2π·√{inner} = {period} s",
    )

    lemma.actual_value = period

    # Dimensionless invariant: T²·g/L = 4π² (universal — independent of L and g).
    # Provides the "Edge cases addressed" structural-insight surface: derivation
    # produces a quantity that, when scaled by the physical parameters, yields a
    # universal constant. Any drift from 4π² ≈ 39.478 signals a math bug.
    dimensionless = (period * period * g) / L
    lemma.add_invariant_check(
        predicate="T²·g/L = 4π² (dimensionless universal)",
        expected_value=4 * math.pi * math.pi,
        actual_value=dimensionless,
        justification=(
            "From T = 2π·√(L/g): T² = 4π²·L/g, so T²·g/L = 4π². Universal across "
            "all pendulum configurations — independent of L and g separately."
        ),
    )

    return lemma


def large_angle_pendulum_period(
    L: float, g: float, theta_0: float, lemma_id: str = "large_angle_pendulum_period",
) -> Lemma:
    """Compute pendulum period for finite amplitude θ₀ via elliptic-integral series.

    Cycle 5 #00P13c5-05 substrate Tier 3 extension. Goes beyond the small-angle
    linearization (`pendulum_period`) by summing the elliptic-integral series in
    k = sin(θ₀/2). Truncated at k⁸ (4 series terms); accurate to ~3e-3 at θ₀ = π/2,
    much tighter at smaller amplitudes. Hand-rolled — uses only `math.sqrt` + `math.pi`
    + `math.sin`; NO scipy.special.ellipk, NO numerical-integration libraries.

    Anti-cheat-aware design (cycle 4 #00P13c4-24 binding):
    Series is computed BOTH via explicit-coefficient form (k² + (9/64)·k⁴ + ...)
    AND via incremental ratio-recursion (a_{n+1} = a_n·((2n+1)/(2n+2))²·k²); the
    two computations must agree post-derivation (built-in algorithmic cross-check).

    Raises ValueError on non-positive L or g, or on |θ₀| ≥ π (full-inversion regime
    is non-oscillatory; out of cycle 5 substrate scope).
    """
    if L <= 0 or g <= 0:
        raise ValueError(f"L and g must be positive (got L={L}, g={g})")
    if abs(theta_0) >= math.pi:
        raise ValueError(
            f"|θ₀| must be < π for oscillatory regime (got θ₀={theta_0}); "
            f"full-inversion not in cycle 5 scope",
        )

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute large-angle pendulum period for L = {L} m, g = {g} m/s², θ₀ = {theta_0} rad.",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_LARGE_ANGLE_PENDULUM)

    # Step 1 — small-angle period T₀ = 2π·√(L/g). Series multiplies this baseline.
    T0 = 2 * math.pi * math.sqrt(L / g)
    lemma.add_step(
        operation="small_angle_period",
        inputs={"L": L, "g": g},
        output=T0,
        justification=f"T₀ = 2π·√(L/g) = 2π·√({L}/{g}) = {T0} s (small-angle baseline)",
    )

    # Step 2 — modulus k = sin(θ₀/2). The series parameter; for small θ₀, k ≈ θ₀/2.
    k = math.sin(theta_0 / 2)
    k2 = k * k
    lemma.add_step(
        operation="elliptic_modulus",
        inputs={"theta_0": theta_0},
        output=k,
        justification=f"k = sin(θ₀/2) = sin({theta_0/2}) = {k}; k² = {k2}",
    )

    # Step 3 — series correction (4-term truncation through k⁸). Explicit coefficients.
    # Coefficients are squared central binomials: [(2n)!/(2²ⁿ·(n!)²)]².
    k4 = k2 * k2
    k6 = k4 * k2
    k8 = k4 * k4
    correction = 1.0 + (1 / 4) * k2 + (9 / 64) * k4 + (25 / 256) * k6 + (1225 / 16384) * k8
    lemma.add_step(
        operation="series_correction",
        inputs={"k2": k2, "k4": k4, "k6": k6, "k8": k8},
        output=correction,
        justification=(
            f"K(k)/K(0) = 1 + (1/4)·k² + (9/64)·k⁴ + (25/256)·k⁶ + (1225/16384)·k⁸ "
            f"= {correction} (4-term truncation; n=4 onward dropped)"
        ),
    )

    # Step 4 — full period.
    period = T0 * correction
    lemma.add_step(
        operation="period",
        inputs={"T0": T0, "correction": correction},
        output=period,
        justification=f"T = T₀·correction = {T0}·{correction} = {period} s",
    )

    lemma.actual_value = period

    # Invariant: leading-order Taylor expansion T - T₀ ≈ T₀·θ₀²/16 holds in small-angle
    # limit. Mirrors cycle 4 #02 relativistic_momentum's β²/2 invariant — exact only as
    # θ₀ → 0; higher-order terms dominate at large amplitude. Tolerance set per-call.
    leading_order_approx = T0 * (theta_0 * theta_0) / 16.0
    relative_correction = period - T0
    lemma.add_invariant_check(
        predicate="T - T₀ ≈ T₀·θ₀²/16 in small-angle limit (textbook leading-order Taylor)",
        expected_value=leading_order_approx,
        actual_value=relative_correction,
        justification=(
            "Textbook expansion: T = T₀·(1 + θ₀²/16 + 11θ₀⁴/3072 + ...). Leading "
            "θ₀²/16 matches series-computation in v << c analog; higher-order terms "
            "dominate at large θ₀, so invariant_check tolerance must be set per-call "
            "(loose at θ₀ ~ π/2; tight at θ₀ ~ 0.1)."
        ),
    )

    return lemma


def relativistic_momentum(
    m: float, v: float, c: float, lemma_id: str = "relativistic_momentum",
) -> Lemma:
    """Compute relativistic momentum p = γ·m·v with γ = 1/√(1 - v²/c²).

    Two-step derivation chain: Lorentz factor γ → momentum γmv. Invariant check:
    Newtonian limit (γ approaches 1 as v << c, giving p → m·v) — verifies the
    relativistic formula reduces to the classical formula in the slow-velocity
    limit (correspondence principle).

    Raises ValueError on non-positive m or c, or on |v| >= c (causal-structure
    violation; cycle 4 scope is subluminal v only).
    """
    if m <= 0 or c <= 0:
        raise ValueError(f"m and c must be positive (got m={m}, c={c})")
    if abs(v) >= c:
        raise ValueError(
            f"|v| must be < c for subluminal regime (got v={v}, c={c}); "
            f"superluminal not in cycle 4 scope",
        )

    lemma = Lemma(
        id=lemma_id,
        claim=f"Compute relativistic momentum for m = {m} kg at v = {v} m/s (c = {c} m/s).",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_RELATIVISTIC_MOMENTUM)

    beta_sq = (v * v) / (c * c)
    gamma = 1.0 / math.sqrt(1 - beta_sq)
    lemma.add_step(
        operation="lorentz_factor",
        inputs={"v": v, "c": c},
        output=gamma,
        justification=(
            f"β² = (v/c)² = ({v}/{c})² = {beta_sq}; γ = 1/√(1 - β²) = 1/√{1 - beta_sq} "
            f"= {gamma}"
        ),
    )

    p = gamma * m * v
    lemma.add_step(
        operation="momentum",
        inputs={"gamma": gamma, "m": m, "v": v},
        output=p,
        justification=f"p = γ·m·v = {gamma}·{m}·{v} = {p} kg·m/s",
    )

    lemma.actual_value = p

    # Newtonian-limit invariant: relativistic p / (m·v) = γ; γ → 1 as v << c.
    # We compute the relative correction (γ - 1) and verify it matches the
    # leading-order Taylor expansion β²/2 = (v/c)²/2 to within tolerance scaling
    # with β² (higher-order terms drift the comparison at relativistic speeds, so
    # the check is meaningful only at low v; in the relativistic regime, the
    # correspondence-principle test isn't a strict equality but a regime check).
    relative_correction = gamma - 1.0
    leading_order_approx = beta_sq / 2.0
    lemma.add_invariant_check(
        predicate="γ - 1 ≈ β²/2 in slow-velocity limit (Newtonian limit / correspondence)",
        expected_value=leading_order_approx,
        actual_value=relative_correction,
        justification=(
            "Taylor expansion: γ = 1 + β²/2 + 3β⁴/8 + ... → γ - 1 ≈ β²/2 in v << c. "
            "Holds exactly in the limit; check confirms substrate produced relativistic "
            "γ, not Newtonian γ=1. At relativistic v (e.g. 0.9c), higher-order terms "
            "dominate — invariant_check tolerance must be set per-call accordingly."
        ),
    )

    return lemma


def projectile_horizontal_range(
    h: float, v_horizontal: float, g: float,
    lemma_id: str = "projectile_horizontal_range",
) -> Lemma:
    """Compute horizontal range R = v_x · √(2h/g) of a cliff-launched horizontal projectile.

    Decouples vertical free-fall (kinematic identity t = √(2h/g)) and horizontal
    uniform motion (no horizontal force; R = v_x · t). Hand-rolled — uses math.sqrt
    only. NO numerical-physics libraries. Closes physics-007 agent-runtime gap.

    Raises ValueError on non-positive h, v_horizontal, or g (regime check; cycle 8
    minimum-viable scope is h>0, v>0, g>0).
    """
    if h <= 0 or v_horizontal <= 0 or g <= 0:
        raise ValueError(
            f"h, v_horizontal, g must all be positive (got h={h}, v_horizontal={v_horizontal}, g={g})"
        )

    lemma = Lemma(
        id=lemma_id,
        claim=(
            f"Compute horizontal range for projectile launched horizontally from "
            f"{h} m at {v_horizontal} m/s under gravity {g} m/s²."
        ),
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_PROJECTILE_HORIZONTAL_RANGE)

    # Step 1: vertical fall time t = √(2h/g) (kinematic identity).
    inner = 2 * h / g
    t = math.sqrt(inner)
    lemma.add_step(
        operation="vertical_fall_time",
        inputs={"h": h, "g": g},
        output=t,
        justification=(
            f"From h = (1/2)·g·t² with v_y(0) = 0: t = √(2h/g) = √(2·{h}/{g}) = "
            f"√{inner} = {t} s."
        ),
    )

    # Step 2: horizontal range R = v_x · t (constant horizontal velocity).
    R = v_horizontal * t
    lemma.add_step(
        operation="horizontal_range",
        inputs={"v_horizontal": v_horizontal, "t": t},
        output=R,
        justification=(
            f"R = v_x · t = {v_horizontal} · {t} = {R} m (constant horizontal velocity; "
            f"no horizontal force; decoupled from vertical motion)."
        ),
    )

    lemma.actual_value = R

    # Universal invariant: R² · g / (2h) = v_horizontal². From R = v_x · √(2h/g):
    # squaring both sides gives R² = v_x² · 2h/g; multiply by g/(2h) → v_x². Universal
    # algebraic identity across all (h, v_x, g) > 0; verifies the substrate's chain
    # composed the two steps consistently. Cycle 9 predicate-strength uniformity pass
    # may swap this for energy-conservation independent-path verifier.
    universal = (R * R * g) / (2 * h)
    v_sq = v_horizontal * v_horizontal
    lemma.add_invariant_check(
        predicate="R² · g / (2h) = v_horizontal² (universal algebraic identity)",
        expected_value=v_sq,
        actual_value=universal,
        justification=(
            "From R = v_x · √(2h/g): R² = v_x²·2h/g → R²·g/(2h) = v_x². Universal "
            "across all (h, v_x, g) > 0 — independent of intermediate t computation."
        ),
    )

    return lemma


def relativistic_doppler_shift(
    wavelength_emit: float,
    beta: float,
    approaching: bool = True,
    lemma_id: str = "relativistic_doppler_shift",
) -> Lemma:
    """Compute relativistic Doppler-shifted wavelength.

    Closed-form: λ_obs = λ_emit · √((1∓β)/(1±β)) where β = v/c, with `-β` in numerator
    for approaching sources (blueshift) and `+β` for receding (redshift). `beta` is the
    dimensionless v/c ratio (typical prompts give v as fraction-of-c directly).

    Hand-rolled — uses math.sqrt only. NO numerical-relativity libraries. Closes
    physics-012 agent-runtime gap.

    Raises ValueError on non-positive wavelength or |β| ≥ 1 (superluminal regime;
    cycle 8 scope is subluminal only).
    """
    if wavelength_emit <= 0:
        raise ValueError(f"wavelength_emit must be positive (got {wavelength_emit})")
    if abs(beta) >= 1.0:
        raise ValueError(
            f"|β| must be < 1 for subluminal regime (got β={beta}); superluminal not in scope"
        )

    direction = "approaching" if approaching else "receding"
    lemma = Lemma(
        id=lemma_id,
        claim=(
            f"Compute relativistic Doppler-shifted wavelength for λ_emit = "
            f"{wavelength_emit} nm at β = {beta} ({direction} source)."
        ),
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_RELATIVISTIC_DOPPLER_SHIFT)

    # Step 1: Doppler factor sqrt((1∓β)/(1±β)) (approaching uses minus in numerator).
    if approaching:
        ratio = (1.0 - beta) / (1.0 + beta)
        factor_form = "√((1-β)/(1+β))"
    else:
        ratio = (1.0 + beta) / (1.0 - beta)
        factor_form = "√((1+β)/(1-β))"
    factor = math.sqrt(ratio)
    lemma.add_step(
        operation="doppler_factor",
        inputs={"beta": beta, "approaching": approaching},
        output=factor,
        justification=(
            f"Doppler factor for {direction} source at β = {beta}: "
            f"{factor_form} = √({ratio}) = {factor}."
        ),
    )

    # Step 2: apply factor to emitted wavelength.
    wavelength_obs = wavelength_emit * factor
    shift_type = "blueshift" if approaching else "redshift"
    compression = "compressed" if approaching else "stretched"
    lemma.add_step(
        operation="apply_factor",
        inputs={"wavelength_emit": wavelength_emit, "factor": factor},
        output=wavelength_obs,
        justification=(
            f"λ_obs = λ_emit · factor = {wavelength_emit} · {factor} = {wavelength_obs} nm "
            f"({shift_type} — wavelength {compression})."
        ),
    )

    lemma.actual_value = wavelength_obs

    # Invariant: factor² = (1∓β)/(1±β). Tautological under the closed-form but verifies
    # the sqrt was applied to the correct ratio (catches sign-flip or denominator bugs).
    # Matches cycle 8 #01/#02/#03/#04 algebraic-identity pattern; classical-Doppler-limit
    # independent-path verifier (factor ≈ 1 ∓ β for β << 1) deferred to cycle 9.
    lemma.add_invariant_check(
        predicate=f"factor² = (1{'∓' if approaching else '±'}β)/(1{'±' if approaching else '∓'}β) (formula consistency)",
        expected_value=ratio,
        actual_value=factor * factor,
        justification=(
            "Squaring the Doppler factor recovers the ratio (1∓β)/(1±β). Tautological "
            "under the closed-form; verifies the substrate computed the correct ratio "
            "before taking the square root (catches sign-flip or denominator bugs)."
        ),
    )

    return lemma
