"""From-scratch symbolic reasoning primitives — Project X Phase 13 cycle 2 (#00P13c2-02).

Lemma chain dataclass + derivation step recorder + closed-form arithmetic primitives
(quadratic solver + 2x2 characteristic polynomial expansion).

Organic-thesis compliance is load-bearing here:
- NO sympy (default-DENY per docs/MANIFESTO.md § Standing orders + DO_THIS_NEXT cycle 2
  encoded decision). sympy IS a symbolic-AI library — counts as "borrowing other tools"
  against the post-transformer thesis. Closed-form arithmetic uses Python stdlib `math`,
  which is a calculator, not a symbolic-AI substrate.
- NO numpy in substrate (the agent's reasoning side). The cycle 2 D3 verifier MAY use
  numpy in the sandbox-side verification SCRIPT it generates, but that's verifier-tooling,
  not substrate-tooling — the script runs in the sandbox subprocess against the agent's
  hand-rolled derivation, confirming correctness.
- NO LLM wrappers anywhere. Output is template-string composition of recorded steps.

This module ships the SUBSTRATE primitives only. The Project X Raphael agent (NOT the
Claude Code Raphael builder) consumes these primitives at inference time to build
gradeable derivations. The verifier (#00P13c2-03) closes the loop by running an
independent numerical computation in the cycle 1 sandbox.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any


@dataclass
class DerivationStep:
    """One step in a Lemma's derivation chain.

    Each step records OPERATION (what computational primitive ran), INPUTS it consumed,
    OUTPUT it produced, and JUSTIFICATION (the WHY this step is valid given prior steps).
    Together these compose a proof-shape audit trail readable as a Raphael-voice
    derivation rendering — see Lemma.render().
    """

    step_index: int
    operation: str
    inputs: dict[str, Any]
    output: Any
    justification: str


@dataclass
class InvariantCheck:
    """A post-derivation invariant check — closes the rubric "edge cases addressed" criterion.

    Phase 13 cycle 3 #00P13c3-02 substrate Tier 1 extension. For closed-form math
    derivations: e.g. trace = sum of eigenvalues; det = product (Vieta's formula).
    Checking these post-derivation is a structural-insight surface: the substrate
    not only computes the answer, it confirms the answer satisfies the canonical
    invariants — which IS the math-WHY for many primitives.

    `holds` is computed numerically with tolerance for floats (long arithmetic
    chains drift by ~ulp; exact equality would false-fail on legitimate matches).
    """

    predicate: str
    expected_value: Any
    actual_value: Any
    holds: bool
    justification: str


@dataclass
class Lemma:
    """A complete claim + derivation chain + verification metadata.

    The agent populates `derivation_steps` and `actual_value` via primitives like
    `solve_quadratic`. The verifier (#00P13c2-03) populates `match` after running an
    independent sandbox computation against `expected_value` (sourced from a ladder
    entry's `auto_grade.expected_*` field).

    Phase 13 cycle 3 #00P13c3-02 Tier 1 extensions:
    - `introduction`: math-WHY prose explaining why the primitive's formula holds
      (vs WHAT the formula does — that's already in derivation_steps). Rendered
      before the step chain. Empty string if not set.
    - `invariant_checks`: post-derivation edge-case verifications (Vieta-style for
      polynomials, sanity checks for matrix ops, etc). Closes the rubric
      "edge cases addressed" criterion.
    """

    id: str
    claim: str
    derivation_steps: list[DerivationStep] = field(default_factory=list)
    verification_method: str = "numerical_close"
    expected_value: Any = None
    actual_value: Any = None
    tolerance: float = 0.001
    match: bool | None = None
    introduction: str = ""
    invariant_checks: list[InvariantCheck] = field(default_factory=list)

    def add_step(
        self,
        operation: str,
        inputs: dict[str, Any],
        output: Any,
        justification: str,
    ) -> DerivationStep:
        step = DerivationStep(
            step_index=len(self.derivation_steps),
            operation=operation,
            inputs=inputs,
            output=output,
            justification=justification,
        )
        self.derivation_steps.append(step)
        return step

    def add_introduction(self, prose: str) -> None:
        """Set the math-WHY prose for this lemma. Renders before derivation steps.

        Closes the rubric "structural insight: does the proof reveal WHY the
        result holds?" criterion. WHY-prose is per-primitive canned text (the
        derivation of the formula from first principles, e.g. completing the
        square for the quadratic formula); not autogenerated.
        """
        self.introduction = prose

    def add_invariant_check(
        self,
        predicate: str,
        expected_value: Any,
        actual_value: Any,
        justification: str,
    ) -> InvariantCheck:
        """Append a post-derivation invariant check; computes `holds` per tolerance.

        For numeric inputs: tolerance-based equality (long chains drift by ulp).
        For non-numeric: exact equality. The check is rendered after the
        derivation chain in `render()` with ✓ / ✗ status.
        """
        if isinstance(expected_value, (int, float)) and isinstance(actual_value, (int, float)):
            holds = abs(expected_value - actual_value) <= self.tolerance
        else:
            holds = expected_value == actual_value
        check = InvariantCheck(
            predicate=predicate,
            expected_value=expected_value,
            actual_value=actual_value,
            holds=holds,
            justification=justification,
        )
        self.invariant_checks.append(check)
        return check

    def render(self) -> str:
        """Render the derivation as a Raphael-voice proof-shape string.

        Output mimics the hand-crafted `raphael_response` shape in the ladder JSONL
        (declarative "Notice." prelude + numbered steps with justification + final
        "Affirmative — <actual_value>" close). Phase 13 cycle 3 Tier 1 extends:
        introduction (math-WHY prose) is prepended if set; invariant_checks are
        appended after the step chain if any. Both sections render only when
        populated — a Lemma without intro/invariants renders identically to
        cycle 2 for backward compat.
        """
        lines = [f"Notice. {self.claim}"]
        if self.introduction:
            lines.append("")
            lines.append(self.introduction)
        lines.append("")
        for step in self.derivation_steps:
            lines.append(f"Step {step.step_index + 1} — {step.operation}: {step.justification}")
            lines.append(f"  Inputs: {step.inputs}")
            lines.append(f"  Output: {step.output}")
        if self.invariant_checks:
            lines.append("")
            lines.append("Invariant checks:")
            for inv in self.invariant_checks:
                mark = "✓" if inv.holds else "✗"
                lines.append(
                    f"  {mark} {inv.predicate}: expected {inv.expected_value}, "
                    f"actual {inv.actual_value} — {inv.justification}",
                )
        lines.append("")
        lines.append(f"Affirmative — {self.actual_value}")
        return "\n".join(lines)


# Math-WHY prose constants for cycle 2 primitives (Tier 1 extension, #00P13c3-02).
# Per-primitive canned text — derivation of the formula from first principles, NOT
# autogenerated. Reused across calls to keep Lemma rendering math-WHY-grounded.
INTRO_QUADRATIC = (
    "Completing the square on ax² + bx + c = 0 yields x = (-b ± √(b² - 4ac)) / 2a. "
    "The discriminant D = b² - 4ac determines the root regime: D > 0 gives two "
    "distinct real roots (the parabola y = ax² + bx + c crosses the x-axis at two "
    "points), D = 0 gives one repeated real root (the parabola touches the x-axis "
    "tangentially), D < 0 gives a complex-conjugate pair (the parabola does not "
    "cross the real axis). Complex roots are out of cycle 2 minimum-viable scope; "
    "substrate raises NotImplementedError when D < 0."
)

INTRO_CHAR_POLY_2X2 = (
    "An eigenvalue λ of A is a scalar such that A - λI is singular: there exists "
    "a non-zero vector v with (A - λI)v = 0, equivalently Av = λv. v is the "
    "corresponding eigenvector — a direction A leaves invariant up to scaling by λ. "
    "Singularity of A - λI is captured by det(A - λI) = 0, the characteristic "
    "polynomial. For 2×2 A this expands to λ² - tr(A)λ + det(A) = 0; eigenvalues "
    "are the roots, and substrate reuses solve_quadratic to find them. The "
    "trace-and-determinant coefficients are no accident: tr(A) = λ₁ + λ₂ and "
    "det(A) = λ₁·λ₂ (Vieta's formula for monic polynomial of degree 2)."
)

INTRO_DETERMINANT_3X3 = (
    "The determinant of a 3×3 matrix A = [[a, b, c], [d, e, f], [g, h, i]] is "
    "computed via Laplace cofactor expansion along any row or column; all "
    "expansions yield the same scalar by algebraic identity. Expanding along "
    "the first row: det(A) = a·(ei - fh) - b·(di - fg) + c·(dh - eg). Each "
    "parenthesized term is a 2×2 minor — the determinant of the 2×2 submatrix "
    "obtained by deleting the row and column containing the cofactor entry. The "
    "alternating signs (+, -, +) come from the (-1)^(i+j) cofactor parity. The "
    "determinant equals the signed volume of the parallelepiped spanned by the "
    "rows (or columns); zero determinant means rows are linearly dependent and "
    "the matrix is singular (non-invertible)."
)


def solve_quadratic(a: float, b: float, c: float, lemma_id: str = "quadratic") -> Lemma:
    """Solve ax² + bx + c = 0 via discriminant + closed-form root formula.

    Hand-rolled — uses only `math.sqrt` (Python stdlib calculator, not a symbolic-AI
    library). Returns a Lemma with the full 3-step derivation chain (discriminant →
    sqrt → root_pair) so D4 grading sees the proof-shape, not just the numerical roots.

    Coverage: real-distinct + real-repeated roots (discriminant >= 0). Complex-conjugate
    roots (discriminant < 0) are out of cycle 2 minimum-viable scope and raise
    NotImplementedError — surfacing the limit explicitly is more honest than silently
    returning a tuple of (real, imag) pairs and pretending the substrate handles them.
    """
    if a == 0:
        raise ValueError("not a quadratic — coefficient a is zero")

    lemma = Lemma(
        id=lemma_id,
        claim=f"Solve {a}x² + {b}x + {c} = 0 for x.",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_QUADRATIC)

    discriminant = b * b - 4 * a * c
    lemma.add_step(
        operation="discriminant",
        inputs={"a": a, "b": b, "c": c},
        output=discriminant,
        justification=f"D = b² - 4ac = ({b})² - 4·{a}·{c} = {discriminant}; sign determines root regime",
    )

    if discriminant < 0:
        raise NotImplementedError(
            f"complex-conjugate roots beyond cycle 2 scope (discriminant = {discriminant})",
        )

    sqrt_d = math.sqrt(discriminant)
    lemma.add_step(
        operation="sqrt",
        inputs={"discriminant": discriminant},
        output=sqrt_d,
        justification=f"√D = √{discriminant} = {sqrt_d}",
    )

    root_pos = (-b + sqrt_d) / (2 * a)
    root_neg = (-b - sqrt_d) / (2 * a)
    roots = sorted([root_pos, root_neg])
    lemma.add_step(
        operation="root_pair",
        inputs={"a": a, "b": b, "sqrt_d": sqrt_d},
        output=roots,
        justification=f"x = (-b ± √D) / 2a = ({-b} ± {sqrt_d}) / {2 * a} → {roots}",
    )

    lemma.actual_value = roots
    return lemma


def expand_characteristic_polynomial_2x2(
    matrix: list[list[float]],
    lemma_id: str = "char_poly_2x2",
) -> Lemma:
    """Compute 2x2 matrix eigenvalues via characteristic polynomial λ² - tr(A)λ + det(A) = 0.

    Reuses `solve_quadratic` — establishes the substrate's compositional discipline:
    each new primitive composes prior primitives rather than reaching for a numerical
    library. Hand-rolled trace + determinant; no `numpy.linalg.eigvals`.

    Composition matters because cycle 3+ extensions (e.g., 3x3 characteristic polynomial,
    Newton's method for higher-degree roots) build on these primitives. If we had imported
    numpy here, the substrate would be a numpy-wrapper rather than an organic computation
    layer — and the thesis would be silently violated.
    """
    if len(matrix) != 2 or any(len(row) != 2 for row in matrix):
        raise ValueError("matrix must be 2x2")

    a, b = matrix[0]
    c, d = matrix[1]

    lemma = Lemma(
        id=lemma_id,
        claim=f"Find eigenvalues of [[{a}, {b}], [{c}, {d}]] via characteristic polynomial.",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_CHAR_POLY_2X2)

    trace = a + d
    lemma.add_step(
        operation="trace",
        inputs={"matrix": matrix},
        output=trace,
        justification=f"tr(A) = a + d = {a} + {d} = {trace}",
    )

    det = a * d - b * c
    lemma.add_step(
        operation="det",
        inputs={"matrix": matrix},
        output=det,
        justification=f"det(A) = ad - bc = {a}·{d} - {b}·{c} = {det}",
    )

    poly_a, poly_b, poly_c = 1.0, -trace, det
    lemma.add_step(
        operation="char_poly_coeffs",
        inputs={"trace": trace, "det": det},
        output={"a": poly_a, "b": poly_b, "c": poly_c},
        justification=f"det(A - λI) = λ² - tr(A)λ + det(A) = λ² - {trace}λ + {det} = 0",
    )

    quad_lemma = solve_quadratic(poly_a, poly_b, poly_c, lemma_id=f"{lemma_id}_quadratic")
    eigenvalues = quad_lemma.actual_value
    lemma.add_step(
        operation="solve_via_quadratic",
        inputs={"polynomial": f"λ² - {trace}λ + {det}"},
        output=eigenvalues,
        justification=f"Eigenvalues = roots of characteristic polynomial = {eigenvalues}",
    )

    lemma.actual_value = eigenvalues

    # Vieta's formula invariants: trace = λ₁ + λ₂; det = λ₁·λ₂.
    # These hold because the char poly is monic of degree 2 with coefficients
    # (1, -trace, det) — by Vieta, sum of roots = trace, product = det.
    sum_of_eigenvalues = eigenvalues[0] + eigenvalues[1]
    product_of_eigenvalues = eigenvalues[0] * eigenvalues[1]
    lemma.add_invariant_check(
        predicate="tr(A) = λ₁ + λ₂",
        expected_value=trace,
        actual_value=sum_of_eigenvalues,
        justification=(
            "Vieta's formula: monic polynomial λ² - trace·λ + det has root-sum equal "
            "to the negation of the linear coefficient, i.e. trace."
        ),
    )
    lemma.add_invariant_check(
        predicate="det(A) = λ₁·λ₂",
        expected_value=det,
        actual_value=product_of_eigenvalues,
        justification=(
            "Vieta's formula: monic polynomial of degree 2 has root-product equal "
            "to the constant coefficient, i.e. det."
        ),
    )

    return lemma


def determinant_3x3(matrix: list[list[float]], lemma_id: str = "determinant_3x3") -> Lemma:
    """Compute 3x3 determinant via Laplace cofactor expansion along the first row.

    For A = [[a, b, c], [d, e, f], [g, h, i]]:
        det(A) = a·(ei - fh) - b·(di - fg) + c·(dh - eg)

    Three 2×2 minors are computed first (sub-determinants obtained by deleting
    row 0 and the i-th column), then combined with alternating cofactor signs.
    Hand-rolled — uses no numpy.linalg, no scipy.

    Cycle 8 #00P13c8-04 minimum-viable scope: 3×3 only. Cycle 8+ extends to n×n
    via recursive cofactor expansion (or, more numerically-friendly, LU decomp)
    as ladder entries require. Closes maths-012 agent-runtime gap.
    """
    if len(matrix) != 3 or any(len(row) != 3 for row in matrix):
        raise ValueError("matrix must be 3x3")

    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    lemma = Lemma(
        id=lemma_id,
        claim=f"Find the determinant of {matrix} via cofactor expansion along row 0.",
        verification_method="numerical_close",
    )
    lemma.add_introduction(INTRO_DETERMINANT_3X3)

    # Step 1: build the 3 minors (2x2 sub-determinants).
    minor_a = e * i - f * h
    minor_b = d * i - f * g
    minor_c = d * h - e * g
    lemma.add_step(
        operation="build_minors",
        inputs={"matrix": matrix},
        output={"M_a": minor_a, "M_b": minor_b, "M_c": minor_c},
        justification=(
            f"Three 2×2 minors from deleting row 0 and column j: "
            f"M_a = e·i - f·h = {e}·{i} - {f}·{h} = {minor_a}; "
            f"M_b = d·i - f·g = {d}·{i} - {f}·{g} = {minor_b}; "
            f"M_c = d·h - e·g = {d}·{h} - {e}·{g} = {minor_c}."
        ),
    )

    # Step 2: cofactor expansion with alternating signs.
    det = a * minor_a - b * minor_b + c * minor_c
    lemma.add_step(
        operation="cofactor_expansion_row_0",
        inputs={"a": a, "b": b, "c": c, "M_a": minor_a, "M_b": minor_b, "M_c": minor_c},
        output=det,
        justification=(
            f"det(A) = a·M_a - b·M_b + c·M_c = {a}·{minor_a} - {b}·{minor_b} + "
            f"{c}·{minor_c} = {a * minor_a} - {b * minor_b} + {c * minor_c} = {det}. "
            f"Alternating signs (+, -, +) from (-1)^(0+j) cofactor parity along row 0."
        ),
    )

    lemma.actual_value = det

    # Invariant: two-step chain output equals the inlined cofactor formula.
    # det = a·(ei - fh) - b·(di - fg) + c·(dh - eg) — tautological under the
    # formula; verifies the intermediate minor-storage and final summation produce
    # the same result as direct in-expression computation. Cycle 9 predicate-
    # strength uniformity pass will swap this for a Sarrus-rule independent-path
    # verifier (algorithmically different formula for 3×3 determinant).
    direct = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    lemma.add_invariant_check(
        predicate="det = a·(ei-fh) - b·(di-fg) + c·(dh-eg) (cofactor formula inlined)",
        expected_value=det,
        actual_value=direct,
        justification=(
            "The two-step chain (build_minors + cofactor_expansion) should equal "
            "the inlined cofactor formula. Tautological under the formula; verifies "
            "the intermediate minor-storage and final summation are implemented "
            "consistently. Cycle 9 lifts this to a Sarrus-rule independent-path "
            "predicate (algebraically equivalent but computed via a different "
            "permutation sum)."
        ),
    )

    return lemma
