"""
Byte Interface Implementation

The universal "Socket" for content-free I/O:
- φ(o): bytes → normalized floats (observation encoder)
- Action decoder: autoregressive GRU → 256-way categorical per byte

This ensures ALL domains use the same interface with no domain-specific processing.
"""

from __future__ import annotations

from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


def phi(observation: torch.Tensor) -> torch.Tensor:
    """
    Universal observation encoder: bytes → normalized floats.

    Converts byte values [0, 255] to float range [-1, 1].
    This is the ONLY allowed preprocessing - no domain-specific tokenizers.

    Args:
        observation: Tensor of byte values, shape [..., n]
                    dtype can be uint8, int, or float

    Returns:
        Normalized floats, shape [..., n], range [-1, 1]
    """
    # Ensure float dtype for computation
    obs_float = observation.float()

    # Normalize: [0, 255] → [-1, 1]
    normalized = (obs_float - 127.5) / 127.5

    return normalized


def phi_inverse(normalized: torch.Tensor) -> torch.Tensor:
    """
    Inverse of phi: normalized floats → bytes.

    Args:
        normalized: Tensor of floats in range [-1, 1]

    Returns:
        Byte values [0, 255] as uint8
    """
    # Denormalize: [-1, 1] → [0, 255]
    bytes_float = (normalized * 127.5) + 127.5

    # Clamp and convert to uint8
    bytes_clamped = torch.clamp(bytes_float, 0, 255)
    return bytes_clamped.to(torch.uint8)


class AutoregressiveActionDecoder(nn.Module):
    """
    Autoregressive action decoder using GRU(128).

    Generates action bytes one at a time, each conditioned on:
    - Hidden state h_t from the substrate
    - Previously generated bytes in the action sequence

    Architecture from BLUEPRINT.md Section 2.7:
    - GRU(128) decoder
    - 16-d byte embeddings
    - 256-way categorical per byte
    """

    def __init__(
        self,
        hidden_dim: int = 512,  # Substrate hidden dim
        decoder_hidden: int = 128,  # GRU decoder hidden
        byte_embed_dim: int = 16,  # Byte embedding dimension
        num_action_bytes: int = 1,  # Default action length
    ):
        super().__init__()

        self.hidden_dim = hidden_dim
        self.decoder_hidden = decoder_hidden
        self.byte_embed_dim = byte_embed_dim
        self.num_action_bytes = num_action_bytes

        # Byte embeddings for conditioning on previous bytes
        self.byte_embedding = nn.Embedding(256, byte_embed_dim)

        # Project substrate hidden state to decoder initial state
        self.h_proj = nn.Linear(hidden_dim, decoder_hidden)

        # GRU decoder
        self.gru = nn.GRU(
            input_size=byte_embed_dim,
            hidden_size=decoder_hidden,
            num_layers=1,
            batch_first=True,
        )

        # Output head: decoder hidden → 256-way categorical
        self.output_head = nn.Linear(decoder_hidden, 256)

        # Start token embedding (for first byte)
        self.start_embed = nn.Parameter(torch.randn(byte_embed_dim))

    def forward(
        self,
        h_t: torch.Tensor,
        num_bytes: Optional[int] = None,
        temperature: float = 1.0,
        greedy: bool = False,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Generate action bytes autoregressively.

        Args:
            h_t: Substrate hidden state, shape [batch, hidden_dim]
            num_bytes: Number of bytes to generate (default: self.num_action_bytes)
            temperature: Sampling temperature (1.0 = normal, <1 = sharper)
            greedy: If True, use argmax instead of sampling

        Returns:
            actions: Generated bytes, shape [batch, num_bytes], dtype=long
            log_probs: Log probabilities, shape [batch, num_bytes]
        """
        batch_size = h_t.size(0)
        num_bytes = num_bytes or self.num_action_bytes

        # Initialize decoder hidden state from substrate
        decoder_h = self.h_proj(h_t).unsqueeze(0)  # [1, batch, decoder_hidden]

        # Start with start token
        current_embed = self.start_embed.unsqueeze(0).expand(batch_size, -1)  # [batch, embed]

        actions = []
        log_probs = []

        for _ in range(num_bytes):
            # GRU step
            current_embed = current_embed.unsqueeze(1)  # [batch, 1, embed]
            gru_out, decoder_h = self.gru(current_embed, decoder_h)

            # Get logits
            logits = self.output_head(gru_out.squeeze(1))  # [batch, 256]

            # Apply temperature
            if temperature != 1.0:
                logits = logits / temperature

            # Sample or greedy
            probs = F.softmax(logits, dim=-1)
            if greedy:
                action = logits.argmax(dim=-1)
            else:
                action = torch.multinomial(probs, 1).squeeze(-1)

            # Compute log probability
            log_prob = F.log_softmax(logits, dim=-1)
            action_log_prob = log_prob.gather(1, action.unsqueeze(-1)).squeeze(-1)

            actions.append(action)
            log_probs.append(action_log_prob)

            # Embed this action for next step
            current_embed = self.byte_embedding(action)  # [batch, embed]

        # Stack results
        actions = torch.stack(actions, dim=1)  # [batch, num_bytes]
        log_probs = torch.stack(log_probs, dim=1)  # [batch, num_bytes]

        return actions, log_probs

    def get_log_prob(
        self,
        h_t: torch.Tensor,
        actions: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute log probabilities for given actions (for PPO).

        Args:
            h_t: Substrate hidden state, shape [batch, hidden_dim]
            actions: Action bytes, shape [batch, num_bytes]

        Returns:
            log_probs: Log probabilities, shape [batch, num_bytes]
        """
        batch_size = h_t.size(0)
        num_bytes = actions.size(1)

        # Initialize decoder hidden state from substrate
        decoder_h = self.h_proj(h_t).unsqueeze(0)

        # Start with start token
        current_embed = self.start_embed.unsqueeze(0).expand(batch_size, -1)

        log_probs = []

        for i in range(num_bytes):
            # GRU step
            current_embed = current_embed.unsqueeze(1)
            gru_out, decoder_h = self.gru(current_embed, decoder_h)

            # Get logits and log probs
            logits = self.output_head(gru_out.squeeze(1))
            log_prob = F.log_softmax(logits, dim=-1)

            # Get log prob for actual action
            action = actions[:, i]
            action_log_prob = log_prob.gather(1, action.unsqueeze(-1)).squeeze(-1)
            log_probs.append(action_log_prob)

            # Embed actual action for next step (teacher forcing)
            current_embed = self.byte_embedding(action)

        return torch.stack(log_probs, dim=1)

    def get_entropy(self, h_t: torch.Tensor, num_bytes: Optional[int] = None) -> torch.Tensor:
        """
        Compute entropy of action distribution (for PPO entropy bonus).

        Args:
            h_t: Substrate hidden state, shape [batch, hidden_dim]
            num_bytes: Number of bytes

        Returns:
            entropy: Mean entropy, shape [batch]
        """
        batch_size = h_t.size(0)
        num_bytes = num_bytes or self.num_action_bytes

        # Initialize decoder hidden state
        decoder_h = self.h_proj(h_t).unsqueeze(0)
        current_embed = self.start_embed.unsqueeze(0).expand(batch_size, -1)

        entropies = []

        for _ in range(num_bytes):
            current_embed = current_embed.unsqueeze(1)
            gru_out, decoder_h = self.gru(current_embed, decoder_h)

            logits = self.output_head(gru_out.squeeze(1))
            probs = F.softmax(logits, dim=-1)
            log_probs = F.log_softmax(logits, dim=-1)

            # Entropy: -sum(p * log(p))
            entropy = -(probs * log_probs).sum(dim=-1)
            entropies.append(entropy)

            # Sample for next step (need some action to continue)
            action = torch.multinomial(probs, 1).squeeze(-1)
            current_embed = self.byte_embedding(action)

        return torch.stack(entropies, dim=1).mean(dim=1)


class ByteInterface(nn.Module):
    """
    Complete byte interface wrapper.

    Combines observation encoding and action decoding
    into a single module for clean integration.
    """

    def __init__(
        self,
        hidden_dim: int = 512,
        decoder_hidden: int = 128,
        byte_embed_dim: int = 16,
        num_action_bytes: int = 1,
    ):
        super().__init__()

        self.action_decoder = AutoregressiveActionDecoder(
            hidden_dim=hidden_dim,
            decoder_hidden=decoder_hidden,
            byte_embed_dim=byte_embed_dim,
            num_action_bytes=num_action_bytes,
        )

    def encode_observation(self, observation: torch.Tensor) -> torch.Tensor:
        """Encode observation bytes to normalized floats."""
        return phi(observation)

    def decode_action(
        self,
        h_t: torch.Tensor,
        num_bytes: Optional[int] = None,
        temperature: float = 1.0,
        greedy: bool = False,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Generate action bytes from hidden state."""
        return self.action_decoder(h_t, num_bytes, temperature, greedy)

    def get_action_log_prob(
        self,
        h_t: torch.Tensor,
        actions: torch.Tensor,
    ) -> torch.Tensor:
        """Get log probabilities for given actions."""
        return self.action_decoder.get_log_prob(h_t, actions)

    def get_action_entropy(
        self,
        h_t: torch.Tensor,
        num_bytes: Optional[int] = None,
    ) -> torch.Tensor:
        """Get action distribution entropy."""
        return self.action_decoder.get_entropy(h_t, num_bytes)
